# Generated by Django 5.2.4 on 2025-07-22 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "slot_index",
                    models.IntegerField(
                        help_text="0~143 (0: 00:00-00:10, 143: 23:50-24:00)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(143),
                        ],
                        verbose_name="슬롯 인덱스",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        help_text="최대 500자까지 입력 가능",
                        max_length=500,
                        verbose_name="메모",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tags.tag",
                        verbose_name="태그",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시간 블록",
                "verbose_name_plural": "시간 블록들",
                "ordering": ["date", "slot_index"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="dashboard_t_user_id_52517b_idx"
                    ),
                    models.Index(
                        fields=["user", "tag"], name="dashboard_t_user_id_63ed85_idx"
                    ),
                ],
                "unique_together": {("user", "date", "slot_index")},
            },
        ),
    ]
