# Generated by Django 5.2.4 on 2025-07-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_rename_dashboard_t_user_id_52517b_idx_idx_user_date_and_more",
        ),
        ("tags", "0003_remove_tag_unique_user_tag_name_tag_is_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tags.tag",
                verbose_name="태그",
            ),
        ),
    ]
