# Generated by Django 5.2.4 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_timeblock_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeblock",
            name="deleted_tag_name",
            field=models.CharField(
                blank=True,
                help_text="태그가 삭제된 경우 원래 태그명을 보존",
                max_length=50,
                null=True,
                verbose_name="삭제된 태그명",
            ),
        ),
    ]
