# Generated by Django 5.2.4 on 2025-08-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_timeblock_deleted_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeblock",
            name="deleted_tag_name",
        ),
    ]
