# Generated by Django 5.2.4 on 2025-07-22 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="최대 50자까지 입력 가능",
                        max_length=50,
                        verbose_name="태그명",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="HEX 색상 코드 (예: #FF5733)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="올바른 HEX 색상 코드를 입력하세요 (예: #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="색상",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그들",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
