# Generated by Django 5.2.4 on 2025-07-22 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"),
                name="unique_user_tag_name",
                violation_error_message="이미 같은 이름의 태그가 존재합니다.",
            ),
        ),
    ]
