# Generated by Django 5.2.4 on 2025-07-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tag_unique_together_tag_unique_user_tag_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="unique_user_tag_name",
        ),
        migrations.AddField(
            model_name="tag",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="관리자가 등록한 모든 사용자 공용 태그",
                verbose_name="기본 태그",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="null이면 기본 태그 (모든 사용자 공용)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="unique_user_tag_name",
                violation_error_message="이미 같은 이름의 태그가 존재합니다.",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("name",),
                name="unique_default_tag_name",
                violation_error_message="이미 같은 이름의 기본 태그가 존재합니다.",
            ),
        ),
    ]
